spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 507214854706-s09tdsu9v85d1qncb4419c265mf2j0m1.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: JrxEwNpiOt9cYpNot0aM
            client-secret: OT2R4uA1pv
            redirect-uri: http://localhost:8080/oauth2/callback/{registrationId}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

          kakao:
            client-id: d227d38f6839c549cdeadda37eeaa977
            client-secret: ge72tYUvgdGMvlEh4zJwYFaGrlNF8SsX
            redirect-uri: http://localhost:8080/oauth2/callback/{registrationId}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect


secret-key: ThisStatementIsJwtSecretKeyDoNotUseThisStatement

logging.level:
  #    org.hibernate.SQL: debug
  org.hibernate.type: trace